[tool.black]
line-length = 79
target-version = ['py38']
skip_string_normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|migrations|settings\.py)/'

[tool.poetry]
name = "yui"
version = "0.0.0"
description = "YUI is Multi-purpose Slack Bot."
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.6.2"
cchardet = "^2.1.4"
async-timeout = "^3.0.1"
sqlalchemy = "^1.3.10"
sqlalchemy-utils = "^0.34.2"
alembic = "^1.3.0"
click = "^7.0"
toml = "^0.10.0"
aiocron = "^1.3"
fuzzywuzzy = {version = "^0.17.0",extras = ["speedup"]}
lxml = "^4.4.1"
cssselect = "^1.1.0"
babel = "^2.7.0"
feedparser = "^5.2.1"
attrdict = "^2.0.1"
tzlocal = "^2.0.0"
python-dateutil = "^2.8.0"
psycopg2-binary = "^2.8.4"
pyppeteer = "^0.0.25"
asyncio-contextmanager = "^1.0.1"
attrs = "^19.3.0"
sympy = "^1.4"
tossi = "^0.3.1"
codecov = {version = "^2.0.15",optional = true}
fake_useragent = "^0.1.11"
scipy = "^1.3.2"
orjson = "^2.2.0"
aiomcache = "^0.6.0"
more-itertools = "^8.2.0"

[tool.poetry.dev-dependencies]
mypy = "^0.740"
pytest = "^5.2.2"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.8.1"
aioresponses = "^0.6.1"
flake8 = "^3.7.9"
flake8-import-order = "^0.18.1"
freezegun = "^0.3.12"
pre-commit = "^2.1.1"
zimports = "^0.2.0"

[tool.poetry.extras]
travis-ci = ["codecov"]

[tool.poetry.scripts]
yui = "yui.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
