[tool.black]
line-length = 79
target-version = ['py38']
skip_string_normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|migrations|settings\.py)/'

[tool.poetry]
name = "yui"
version = "0.0.0"
description = "YUI is Multi-purpose Slack Bot."
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.0"
cchardet = "^2.1.7"
async-timeout = "^3.0.1"
sqlalchemy = "^1.3.20"
sqlalchemy-utils = "^0.36.8"
alembic = "^1.4.3"
click = "^7.1.2"
toml = "^0.10.2"
aiocron = "^1.3"
fuzzywuzzy = {version = "^0.18.0",extras = ["speedup"]}
lxml = "^4.6.1"
cssselect = "^1.1.0"
babel = "^2.8.0"
feedparser = "^6.0.2"
attrdict = "^2.0.1"
tzlocal = "^2.1"
python-dateutil = "^2.8.1"
psycopg2-binary = "^2.8.6"
pyppeteer = "^0.2.2"
asyncio-contextmanager = "^1.0.1"
attrs = "^20.3.0"
sympy = "^1.6.2"
tossi = "^0.3.1"
codecov = {version = "^2.1.10",optional = true}
fake_useragent = "^0.1.11"
scipy = "^1.5.4"
orjson = "^3.4.3"
aiomcache = "^0.6.0"
more-itertools = "^8.6.0"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
pytest = "^6.1.2"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.10.1"
aioresponses = "^0.7.1"
flake8 = "^3.8.4"
flake8-import-order = "^0.18.1"
freezegun = "^1.0.0"
pre-commit = "^2.8.2"
zimports = "^0.2.2"
black = "^20.8b1"

[tool.poetry.extras]
travis-ci = ["codecov"]

[tool.poetry.scripts]
yui = "yui.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
